from enum import Enum

from nmigen import Array, Value


class OLED_INIT(Enum):
    NOP1 = 0xBC
    NOP2 = 0xBD
    NOP3 = 0xE3
    SET_DISPLAY_OFF = 0xAE
    SET_REMAP_COLOR = 0xA0
    ULX3S_REMAP = 0b00100010 #A[7:6] = 00; 256 color. A[7:6] = 01; 65K color format rotation for ULX3S, A[1] = 1 scan right to left
    SET_DISPLAY_START_LINE = 0xA1
    SET_DISPLAY_OFFSET = 0xA1
    SET_DISPLAY_MODE_NORMAL = 0xA4
    SET_MULTIPLEX_RATIO = 0xA8
    SET_MASTER_CONFIGURATION = 0xAD
    SET_POWER_SAVE_MODE = 0xB0
    SET_PHASE_1_AND_2_PERIOD_ADJUSTMENT = 0xB1
    SET_DISPLAY_CLOCK_DIVIDER = 0xB3
    SET_PRECHARGE_A = 0x8A
    SET_PRECHARGE_B = 0x8B
    SET_PRECHARGE_C = 0x8C
    SET_PRECHARGE_LEVEL = 0xBB
    SET_VCOMH = 0xBE
    SET_MASTER_CURRENT_CONTROL = 0x87
    SET_CONTRAST_COLOR_A = 0x81
    SET_CONTRAST_COLOR_B = 0x82
    SET_CONTRAST_COLOR_C = 0x83
    SET_COLUMN_ADDRESS = 0x15
    SET_ROW_ADDRESS = 0x75
    SET_DISPLAY_ON = 0xAF


oled_init_seq_list = [
    OLED_INIT.NOP1,
    OLED_INIT.SET_DISPLAY_OFF,
    OLED_INIT.SET_REMAP_COLOR, OLED_INIT.ULX3S_REMAP,
    OLED_INIT.SET_DISPLAY_START_LINE, 0x00,
    OLED_INIT.SET_DISPLAY_OFFSET, 0x00,
    OLED_INIT.SET_DISPLAY_MODE_NORMAL,
    OLED_INIT.SET_MULTIPLEX_RATIO, 0b00111111,
    OLED_INIT.SET_MASTER_CONFIGURATION, 0b10001110,
    OLED_INIT.SET_POWER_SAVE_MODE, 0x00,
    OLED_INIT.SET_PHASE_1_AND_2_PERIOD_ADJUSTMENT, 0x74,
    OLED_INIT.SET_DISPLAY_CLOCK_DIVIDER, 0xF0,
    OLED_INIT.SET_PRECHARGE_A, 0x64,
    OLED_INIT.SET_PRECHARGE_B, 0x78,
    OLED_INIT.SET_PRECHARGE_C, 0x64,
    OLED_INIT.SET_PRECHARGE_LEVEL, 0x31,
    OLED_INIT.SET_CONTRAST_COLOR_A, 0xFF,
    OLED_INIT.SET_CONTRAST_COLOR_B, 0xFF,
    OLED_INIT.SET_CONTRAST_COLOR_C, 0xFF,
    OLED_INIT.SET_VCOMH, 0x3E,
    OLED_INIT.SET_MASTER_CURRENT_CONTROL, 0x06,
    OLED_INIT.SET_COLUMN_ADDRESS, 0x00, 0x5F,
    OLED_INIT.SET_ROW_ADDRESS, 0x00, 0x3F,
    OLED_INIT.SET_DISPLAY_ON,
    OLED_INIT.NOP1,
]

oled_init_seq = Array(Value for _ in range(len(oled_init_seq_list)))
for i in range(len(oled_init_seq_list)):
    oled_init_seq[i] = oled_init_seq_list[i]
